language: C++

dist: trusty

sudo: required

services:
    - docker

compiler: gcc

before_install:
    - docker pull ubuntu

install: 
    - docker run ubuntu /bin/sh -c "./install_deps_xenial_sudo.sh; ./testAll -v"

script:
    - ls
