language: C++

dist: trusty

sudo: required

compiler: gcc

install: ./install_deps_trusty_sudo.sh

script:
    - ./travis/release.sh
    - cd build-release
    - ctest -V
    - cd ..
    - ./travis/debug.sh
    - cd build-debug
    - ctest -V
    - cd ..
